# Generated by Django 6.0.2 on 2026-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('total_seasons', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(default=0)),
                ('cast_count', models.IntegerField(default=0)),
                ('cast_details', models.JSONField(default=list)),
                ('trailer_url', models.URLField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('detail_path', models.CharField(max_length=500)),
                ('subject_id', models.CharField(max_length=100)),
                ('play_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
