# Generated by Django 6.0.2 on 2026-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='subject_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
