# Generated by Django 6.0.2 on 2026-02-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_tvseries_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='cast_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
