# Generated by Django 6.0.2 on 2026-02-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_tvseries_cast_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseries',
            name='cast_count',
        ),
        migrations.AddField(
            model_name='tvseries',
            name='season_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='detail_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='play_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='subject_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
