# Generated by Django 6.0.2 on 2026-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_tvseries_cast_count_tvseries_season_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='cover_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='detail_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='play_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='subject_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='trailer_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
