# Generated by Django 6.0.2 on 2026-02-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_tvseries_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseries',
            name='is_homepage',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
