# Generated by Django 6.0.2 on 2026-02-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_tvseries_is_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseries',
            name='is_homepage',
        ),
    ]
