# Generated by Django 6.0.2 on 2026-02-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepageitem_is_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageitem',
            name='season_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepageitem',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
