# Generated by Django 6.0.2 on 2026-02-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homepageitem_season_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageitem',
            name='is_homepage',
        ),
    ]
