# Generated by Django 6.0.2 on 2026-02-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_homepageitem_is_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageitem',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
