# Generated by Django 6.0.2 on 2026-02-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_homepageitem_is_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='homepageitem',
            name='cast_details',
        ),
        migrations.RemoveField(
            model_name='homepageitem',
            name='is_homepage',
        ),
        migrations.RemoveField(
            model_name='homepageitem',
            name='season_details',
        ),
        migrations.RemoveField(
            model_name='homepageitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='homepageitem',
            name='is_banner',
            field=models.BooleanField(default=False, help_text='Show this item as a homepage banner'),
        ),
        migrations.AlterField(
            model_name='homepageitem',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=50),
        ),
    ]
