# Generated by Django 6.0.2 on 2026-02-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_movie_delete_homepageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series'), ('Other', 'Other')], default='Movie', max_length=20)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('imdb_rating', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('detail_path', models.CharField(blank=True, max_length=255)),
                ('trailer', models.URLField(blank=True)),
                ('dubs', models.JSONField(blank=True, default=list)),
                ('cast', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
