# Generated by Django 6.0.2 on 2026-02-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_homepagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('subject_type', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_votes', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('detail_path', models.TextField(blank=True, null=True)),
                ('corner', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('BANNER', 'Banner'), ('FILTER', 'Categories'), ('SPORT_LIVE', 'Live'), ('SUBJECTS_MOVIE', 'Movies/Series'), ('CUSTOM', 'Custom'), ('APPOINTMENT_LIST', 'Upcoming')], max_length=50)),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('section_type', 'position')},
            },
        ),
        migrations.DeleteModel(
            name='homepagemodel',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
