# Generated by Django 6.0.2 on 2026-02-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_homepageitem_homepagesection_delete_homepagemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageitem',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='homepageitem',
            name='episodes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='homepageitem',
            name='play_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepageitem',
            name='seasons',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='homepageitem',
            name='trailer_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
