# Generated by Django 6.0.2 on 2026-02-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_homepageitem_cast_homepageitem_episodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageitem',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='homepageitem',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='homepageitem',
            name='play_url',
        ),
        migrations.RemoveField(
            model_name='homepageitem',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='homepageitem',
            name='trailer_url',
        ),
    ]
