# Generated by Django 6.0.2 on 2026-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_remove_homepageitem_cast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdb', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('cast', models.JSONField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('play_url', models.URLField(blank=True, null=True)),
                ('subject_id', models.CharField(max_length=50, unique=True)),
                ('detail_path', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomepageItem',
        ),
        migrations.DeleteModel(
            name='HomepageSection',
        ),
    ]
