# Generated by Django 6.0.2 on 2026-02-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb_rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cast_details', models.JSONField(blank=True, default=list)),
                ('trailer_url', models.TextField(blank=True, null=True)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('detail_path', models.TextField(blank=True, null=True)),
                ('subject_id', models.TextField(unique=True)),
                ('play_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
    ]
