# Generated by Django 6.0.2 on 2026-02-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviescraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_homepage',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
